// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"time"
)

// CatalogMock is a mock implementation of turn.Catalog.
//
//	func TestSomethingThatUsesCatalog(t *testing.T) {
//
//		// make and configure a mocked turn.Catalog
//		mockedCatalog := &CatalogMock{
//			SelectFunc: func(cwd string, since time.Time, prompt string) (string, error) {
//				panic("mock out the Select method")
//			},
//			SizesFunc: func(cwd string) (map[string]int64, error) {
//				panic("mock out the Sizes method")
//			},
//		}
//
//		// use mockedCatalog in code that requires turn.Catalog
//		// and then make assertions.
//
//	}
type CatalogMock struct {
	// SelectFunc mocks the Select method.
	SelectFunc func(cwd string, since time.Time, prompt string) (string, error)

	// SizesFunc mocks the Sizes method.
	SizesFunc func(cwd string) (map[string]int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// Select holds details about calls to the Select method.
		Select []struct {
			// Cwd is the cwd argument value.
			Cwd string
			// Since is the since argument value.
			Since time.Time
			// Prompt is the prompt argument value.
			Prompt string
		}
		// Sizes holds details about calls to the Sizes method.
		Sizes []struct {
			// Cwd is the cwd argument value.
			Cwd string
		}
	}
	lockSelect sync.RWMutex
	lockSizes  sync.RWMutex
}

// Select calls SelectFunc.
func (mock *CatalogMock) Select(cwd string, since time.Time, prompt string) (string, error) {
	if mock.SelectFunc == nil {
		panic("CatalogMock.SelectFunc: method is nil but Catalog.Select was just called")
	}
	callInfo := struct {
		Cwd    string
		Since  time.Time
		Prompt string
	}{
		Cwd:    cwd,
		Since:  since,
		Prompt: prompt,
	}
	mock.lockSelect.Lock()
	mock.calls.Select = append(mock.calls.Select, callInfo)
	mock.lockSelect.Unlock()
	return mock.SelectFunc(cwd, since, prompt)
}

// SelectCalls gets all the calls that were made to Select.
// Check the length with:
//
//	len(mockedCatalog.SelectCalls())
func (mock *CatalogMock) SelectCalls() []struct {
	Cwd    string
	Since  time.Time
	Prompt string
} {
	var calls []struct {
		Cwd    string
		Since  time.Time
		Prompt string
	}
	mock.lockSelect.RLock()
	calls = mock.calls.Select
	mock.lockSelect.RUnlock()
	return calls
}

// Sizes calls SizesFunc.
func (mock *CatalogMock) Sizes(cwd string) (map[string]int64, error) {
	if mock.SizesFunc == nil {
		panic("CatalogMock.SizesFunc: method is nil but Catalog.Sizes was just called")
	}
	callInfo := struct {
		Cwd string
	}{
		Cwd: cwd,
	}
	mock.lockSizes.Lock()
	mock.calls.Sizes = append(mock.calls.Sizes, callInfo)
	mock.lockSizes.Unlock()
	return mock.SizesFunc(cwd)
}

// SizesCalls gets all the calls that were made to Sizes.
// Check the length with:
//
//	len(mockedCatalog.SizesCalls())
func (mock *CatalogMock) SizesCalls() []struct {
	Cwd string
} {
	var calls []struct {
		Cwd string
	}
	mock.lockSizes.RLock()
	calls = mock.calls.Sizes
	mock.lockSizes.RUnlock()
	return calls
}
