// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/fya/app/ready"
)

// ReadinessMock is a mock implementation of turn.Readiness.
//
//	func TestSomethingThatUsesReadiness(t *testing.T) {
//
//		// make and configure a mocked turn.Readiness
//		mockedReadiness := &ReadinessMock{
//			BlockedFunc: func(output string) bool {
//				panic("mock out the Blocked method")
//			},
//			WaitFunc: func(contextMoqParam context.Context, source ready.Source) (ready.Result, error) {
//				panic("mock out the Wait method")
//			},
//		}
//
//		// use mockedReadiness in code that requires turn.Readiness
//		// and then make assertions.
//
//	}
type ReadinessMock struct {
	// BlockedFunc mocks the Blocked method.
	BlockedFunc func(output string) bool

	// WaitFunc mocks the Wait method.
	WaitFunc func(contextMoqParam context.Context, source ready.Source) (ready.Result, error)

	// calls tracks calls to the methods.
	calls struct {
		// Blocked holds details about calls to the Blocked method.
		Blocked []struct {
			// Output is the output argument value.
			Output string
		}
		// Wait holds details about calls to the Wait method.
		Wait []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Source is the source argument value.
			Source ready.Source
		}
	}
	lockBlocked sync.RWMutex
	lockWait    sync.RWMutex
}

// Blocked calls BlockedFunc.
func (mock *ReadinessMock) Blocked(output string) bool {
	if mock.BlockedFunc == nil {
		panic("ReadinessMock.BlockedFunc: method is nil but Readiness.Blocked was just called")
	}
	callInfo := struct {
		Output string
	}{
		Output: output,
	}
	mock.lockBlocked.Lock()
	mock.calls.Blocked = append(mock.calls.Blocked, callInfo)
	mock.lockBlocked.Unlock()
	return mock.BlockedFunc(output)
}

// BlockedCalls gets all the calls that were made to Blocked.
// Check the length with:
//
//	len(mockedReadiness.BlockedCalls())
func (mock *ReadinessMock) BlockedCalls() []struct {
	Output string
} {
	var calls []struct {
		Output string
	}
	mock.lockBlocked.RLock()
	calls = mock.calls.Blocked
	mock.lockBlocked.RUnlock()
	return calls
}

// Wait calls WaitFunc.
func (mock *ReadinessMock) Wait(contextMoqParam context.Context, source ready.Source) (ready.Result, error) {
	if mock.WaitFunc == nil {
		panic("ReadinessMock.WaitFunc: method is nil but Readiness.Wait was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Source          ready.Source
	}{
		ContextMoqParam: contextMoqParam,
		Source:          source,
	}
	mock.lockWait.Lock()
	mock.calls.Wait = append(mock.calls.Wait, callInfo)
	mock.lockWait.Unlock()
	return mock.WaitFunc(contextMoqParam, source)
}

// WaitCalls gets all the calls that were made to Wait.
// Check the length with:
//
//	len(mockedReadiness.WaitCalls())
func (mock *ReadinessMock) WaitCalls() []struct {
	ContextMoqParam context.Context
	Source          ready.Source
} {
	var calls []struct {
		ContextMoqParam context.Context
		Source          ready.Source
	}
	mock.lockWait.RLock()
	calls = mock.calls.Wait
	mock.lockWait.RUnlock()
	return calls
}
